id: hl7.fhir.uv.apix
canonical: http://hl7.org/fhir/uv/apix
name: ApixIG
title: API for the Exchange of Medicinal Product Information (APIX)
description: A global standard for real-time, API-based exchange of biopharmaceutical regulatory information (e.g., drug labeling and drug quality).
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/
  # email: test@example.org

parameters:
  - code: joy
    value: "true"
  - code: show-summary-table
    value: "true"
  - code: path-resource
    value: input/resources
  - code: path-pages
    value: input/pagecontent
  - code: path-liquid
    value: template/liquid
  - code: path-qa
    value: temp/qa
  - code: path-temp
    value: temp/pages
  - code: path-output
    value: output
  - code: path-tx-cache
    value: input-cache/txcache
  - code: path-suppressed-warnings
    value: input/ignoreWarnings.txt
  - code: path-history
    value: http://hl7.org/fhir/uv/apix/history.html
  - code: template-html
    value: template/index.html
  - code: template-md
    value: template/page.html
  - code: apply-contact
    value: "true"
  - code: apply-jurisdiction
    value: "true"
  - code: apply-publisher
    value: "true"
  - code: apply-version
    value: "true"
  - code: active-tables
    value: "true"
  - code: fhire-wg
    value: brr

pages:
  index.md:
    title: IG Home
  usecases.md:
    title: Use Cases
  apixtask.md:
    title: APIX Task Structure
  workflow.md:
    title: Workflow Example
  subscriptions.md:
    title: Real-Time Subscriptions
  architecture.md:
    title: Architecture

menu:
  IG Home: index.html
  Use Cases: usecases.html
  APIX Task Structure: apixtask.html
  Workflow Example: workflow.html
  Real-Time Subscriptions: subscriptions.html
  Architecture: architecture.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true 