id: hl7.fhir.uv.rtq-ig
canonical: http://hl7.org/fhir/uv/rtq-ig
name: ApixIG
title: API for the Exchange of Medicinal Product Information (APIX)
description: A global standard for real-time, API-based exchange of biopharmaceutical regulatory information (e.g., drug labeling and drug quality).
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Gravitate Health Project
  url: https://www.gravitatehealth.eu/
  # email: test@example.org

pages:
  index.md:
    title: IG Home
  usecases.md:
    title: Use Cases
  apixtask.md:
    title: How to Build APIX Tasks
  workflow.md:
    title: Workflow Overview
  architecture.md:
    title: Architecture
  highvolume.md:
    title: High Volume
  mediumvolume.md:
    title: Medium Volume
  lowvolume.md:
    title: Low Volume
  downloads.md:
    title: Downloads

menu:
  IG Home: index.html
  Use Cases: usecases.html
  APIX Tasks Structure: apixtask.html
  Workflow: workflow.html
  Architecture:
    Overview: architecture.html
    Low Volume: lowvolume.html
    Medium Volume: mediumvolume.html
    High Volume: highvolume.html
  Artifacts: artifacts.html
  Downloads: downloads.html

instanceOptions:
  manualSliceOrdering: true 